### ISSUE TITLE
NPE in StandardRepresentation for maps with null entries

### ISSUE THREAD

**Issue by tkruse** [assertj/doc#144]
This should happen fairly rarely, i saw it occur in an implementation that tried to implement a Map class that provides access to subclass fields via reflection over the map interface.

Using AssertJ 3.24.2 on Java8:
```
java.lang.NullPointerException
	at org.assertj.core.presentation.StandardRepresentation.toStringOf(StandardRepresentation.java:491)
	at org.assertj.core.presentation.StandardRepresentation.toStringOf(StandardRepresentation.java:236)
	at org.assertj.core.presentation.CompositeRepresentation.toStringOf(CompositeRepresentation.java:40)
        ...
```

To reproduce:
```
public class NullEntryMapTest {

    static class NullEntryMap<K, V> extends ConcurrentHashMap<K, V> {
        @Override
        public Set<Entry<K, V>> entrySet() {
            Set<Map.Entry<K, V>> set = new HashSet<>();
            set.add(null);
            return set;
        }
    }

    @Test
    public void testStandardRepresentationWithNullEntryMap() {
        StandardRepresentation.STANDARD_REPRESENTATION.toStringOf(new NullEntryMap<>());
    }

    @Test
    public void testContains() {
        assertThat(new NullEntryMap<>()).containsKey("foo"); // actual assertion does not matter
    }
}
```

To fix, StandardRepresentation should check the entry is not null.
It might be good to also check other occurences of entry.getKey() /entry.getValue() in the code.

I notice IntelliJ as an example handles this case in it's representation of maps.

**Comment by tkruse** [comment]
wrong subproject
